// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-EvhPKy5zif1hhvuZjaxv3iQz1wX9yBw',
    appId: '1:267940741524:android:2b1313515897b2ecf2cf81',
    messagingSenderId: '267940741524',
    projectId: 'dmsqltn-faea3',
    databaseURL: 'https://dmsqltn-faea3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dmsqltn-faea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd8afsr7qlf4P79HaOoM6RvKJQ2MOGZow',
    appId: '1:267940741524:ios:e7b799e4332c7c78f2cf81',
    messagingSenderId: '267940741524',
    projectId: 'dmsqltn-faea3',
    databaseURL: 'https://dmsqltn-faea3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dmsqltn-faea3.appspot.com',
    iosClientId: '267940741524-o2gftk6rr4asp74ctn6vg0d14p3d18ch.apps.googleusercontent.com',
    iosBundleId: 'com.choyeongwoo.dmsqltn',
  );
}
